version: '3.7'
services:
  backend:
    image: node:16
    container_name: backend
    restart: always
    command: sh -c "yarn && yarn docker:debug"
    ports:
      - 3600:3600
      - 5555:5555
      - 9229:9229
    working_dir: /server
    links:
      - postgres
    volumes:
      - ./server/:/server
      - ignorebackend:/server/node_modules

  frontend:
      image: node:16
      container_name: frontend
      restart: always
      command: sh -c "yarn && yarn dev"
      ports:
      - 3000:3000
      working_dir: /client
      links:
      - postgres
      volumes:
      - ./client/:/client
      - ignorefrontend:/client/node_modules


  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
  ignorefrontend:
  ignorebackend:
